### ISSUE TITLE
Incomplete sentence

### ISSUE THREAD

**Issue by erocarrera** [bob-carpenter/stan-getting-started#3]
The sentence "as Stan records every operation with links to its operands during." ends abruptly.

https://github.com/bob-carpenter/stan-getting-started/blob/463091dbfa503548096c5dcfcaba3a1d95364d68/quarto/stan-getting-started.qmd#LL3409C24-L3410C20

**Comment by bob-carpenter** [comment]
Thanks.  I fixed that in the most recent push with "each evaluation of the log density".
